"""Add foreign keys to finding_patterns

Revision ID: ab4f703145e2
Revises: b62720445820
Create Date: 2025-11-06 12:28:00.667155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4f703145e2'
down_revision = 'b62720445820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'finding_patterns', 'patterns', ['pattern_id'], ['id'])
    op.create_foreign_key(None, 'finding_patterns', 'findings', ['finding_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finding_patterns', type_='foreignkey')
    op.drop_constraint(None, 'finding_patterns', type_='foreignkey')
    # ### end Alembic commands ###
