"""Initial schema with all models

Revision ID: b62720445820
Revises: 
Create Date: 2025-11-06 11:25:21.806628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62720445820'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('high_count', sa.Integer(), nullable=True),
    sa.Column('medium_count', sa.Integer(), nullable=True),
    sa.Column('low_count', sa.Integer(), nullable=True),
    sa.Column('ewma_baselines', sa.JSON(), nullable=True),
    sa.Column('count_history', sa.JSON(), nullable=True),
    sa.Column('spike_findings', sa.JSON(), nullable=True),
    sa.Column('top_errors', sa.JSON(), nullable=True),
    sa.Column('top_apps', sa.JSON(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_analysis_time_ms', sa.Float(), nullable=True),
    sa.Column('total_analyses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_id'), 'analysis_history', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_history_timestamp'), 'analysis_history', ['timestamp'], unique=False)
    op.create_table('ewma_baselines',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('current_ewma', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('count_history', sa.JSON(), nullable=True),
    sa.Column('last_count', sa.Integer(), nullable=True),
    sa.Column('spike_threshold_multiplier', sa.Float(), nullable=True),
    sa.Column('last_spike_detected', sa.DateTime(), nullable=True),
    sa.Column('spike_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('samples_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    op.create_index(op.f('ix_ewma_baselines_fingerprint'), 'ewma_baselines', ['fingerprint'], unique=False)
    op.create_table('finding_patterns',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('finding_id', 'pattern_id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('container', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('normalized_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('level_value', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('similar_incidents', sa.JSON(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('feedback_timestamp', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_app_name'), 'findings', ['app_name'], unique=False)
    op.create_index(op.f('ix_findings_created_at'), 'findings', ['created_at'], unique=False)
    op.create_index(op.f('ix_findings_fingerprint'), 'findings', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_findings_first_seen'), 'findings', ['first_seen'], unique=False)
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_index(op.f('ix_findings_last_seen'), 'findings', ['last_seen'], unique=False)
    op.create_index(op.f('ix_findings_level'), 'findings', ['level'], unique=False)
    op.create_index(op.f('ix_findings_namespace'), 'findings', ['namespace'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regex_pattern', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('app_filter', sa.JSON(), nullable=True),
    sa.Column('namespace_filter', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_matched', sa.DateTime(), nullable=True),
    sa.Column('auto_ignore', sa.Boolean(), nullable=True),
    sa.Column('auto_action', sa.JSON(), nullable=True),
    sa.Column('standard_recommendations', sa.JSON(), nullable=True),
    sa.Column('root_cause_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_created_at'), 'patterns', ['created_at'], unique=False)
    op.create_index(op.f('ix_patterns_id'), 'patterns', ['id'], unique=False)
    op.create_index(op.f('ix_patterns_pattern_hash'), 'patterns', ['pattern_hash'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('correct_root_cause', sa.Text(), nullable=True),
    sa.Column('correct_severity', sa.String(length=20), nullable=True),
    sa.Column('resolution_applied', sa.Text(), nullable=True),
    sa.Column('time_to_resolve', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('pattern_updated', sa.Integer(), nullable=True),
    sa.Column('threshold_adjusted', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_feedback_type'), 'feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_feedback_finding_id'), 'feedback', ['finding_id'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_submitted_at'), 'feedback', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_submitted_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_finding_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_type'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_patterns_pattern_hash'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_id'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_created_at'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_findings_namespace'), table_name='findings')
    op.drop_index(op.f('ix_findings_level'), table_name='findings')
    op.drop_index(op.f('ix_findings_last_seen'), table_name='findings')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_first_seen'), table_name='findings')
    op.drop_index(op.f('ix_findings_fingerprint'), table_name='findings')
    op.drop_index(op.f('ix_findings_created_at'), table_name='findings')
    op.drop_index(op.f('ix_findings_app_name'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('finding_patterns')
    op.drop_index(op.f('ix_ewma_baselines_fingerprint'), table_name='ewma_baselines')
    op.drop_table('ewma_baselines')
    op.drop_index(op.f('ix_analysis_history_timestamp'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_id'), table_name='analysis_history')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
