apiVersion: v1
kind: Secret
metadata:
  name: ai-log-analyzer-secret
  namespace: ai-log-analyzer
  labels:
    app: ai-log-analyzer
    managed-by: kbcloud-squad-sq016
type: Opaque
stringData:
  # Database connection (Cyberark references)
  DATABASE_HOST: "P050TD01.DEV.KB.CZ"  # TODO: Verify NPROD host after testing
  DATABASE_USER: |
    conjur:epv/CAR_TA_LOBUser_TEST/DAP_PCB/DAP_PCB/ailog-db-user/username
  DATABASE_PASSWORD: |
    conjur:epv/CAR_TA_LOBUser_TEST/DAP_PCB/DAP_PCB/ailog-db-user/password

  # Elasticsearch (already tested connectivity)
  ES_URL: "https://elasticsearch-test.kb.cz:9500"
  ES_USER: |
    conjur:epv/CAR_TA_LOBUser_TEST/DAP_PCB/DAP_PCB/XX_PCBS_ES_READ/username
  ES_PASSWORD: |
    conjur:epv/CAR_TA_LOBUser_TEST/DAP_PCB/DAP_PCB/XX_PCBS_ES_READ/password

  # OpenAI API key (optional - if using instead of local LLM)
  # OPENAI_API_KEY: |
  #   conjur:...
